name: CI
on: [push]
env:
  CI: true
  API_KEY: ${{ secrets.API_KEY }}
  CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.1.3]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run tests with code coverage
      run: COVERAGE=true bundle exec rake test
    - name: Install Code Climate Test Reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
      working-directory: ${{ github.workspace }}
    - name: Push coverage data to Code Climate
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: |
        ./cc-test-reporter before-build
        ./cc-test-reporter after-build --exit-code $?
      working-directory: ${{ github.workspace }}

